### ISSUE TITLE
`api.store` and `store.getContentType()` deprecation warnings

### ISSUE THREAD

**Issue by codybarr** [darthmeme/gridsome-plugin-rss#14]
On build with the more recent versions of Gridsome (currently 0.7.12) I'm getting the following errors from the `gridsome-plugin-rss` plugin:

```
Avoid using api.store directly. Use the actions in api.loadSource() instead.
./node_modules/gridsome-plugin-rss/index.js:6:22                            
                                                                            
The store.getContentType() method has been renamed to store.getCollection().
./node_modules/gridsome-plugin-rss/index.js:8:34  
```

Still successfully building atm but I'm not sure how long this will continue to work as it looks like these two things have been changed.

**Comment by brandonpittman** [comment]
Time to fork this bad boy.

**Comment by rasulkireev** [comment]
My build is successfull localy, but fails on the server (Netlify). I suspect this might be the reason.

**Comment by Tragio** [comment]
Hello @darthmeme, really thank you for your plugin! Would be possible to update the plugin to fix these warnings so we can keep using your plugin in the future? 😃

**Comment by GeorgeGedox** [comment]
Could we get an update on this please? Thank you

**Comment by darthmeme** [comment]
@GeorgeGedox - I unfortunately don't have time to update this. If you'd like to open a PR, I'd be more than happy to merge & release it.

**Comment by GeorgeGedox** [comment]
> @GeorgeGedox - I unfortunately don't have time to update this. If you'd like to open a PR, I'd be more than happy to merge & release it.

I'm not familiar with the plugin development for gridsome but I'll try my hand at fixing this over the week.

**Comment by darthmeme** [comment]
@GeorgeGedox v1.4.0 published! Thanks for your help, much appreciated!
